version: "3.9"

services:
web:
  build: .
  volumes:
    - .:/app
    - ./data:/app/db  # Garante que o SQLite fique persistente
    - ./staticfiles:/app/staticfiles
  ports:
    - "8000:8000"
  env_file:
    - .env
