# Generated by Django 5.2.3 on 2025-06-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="theme",
            field=models.CharField(default="light", max_length=5),
        ),
    ]
