# Generated by Django 5.2.2 on 2025-06-18 20:28

from django.db import migrations, models
import random


def update_accounts(apps, schema_editor):
    Account = apps.get_model("core", "Account")
    existing = set(Account.objects.values_list("account_number", flat=True))
    for account in Account.objects.all():
        if len(account.account_number) <= 5 and account.account_number.isdigit():
            continue
        while True:
            num = str(random.randint(10000, 99999))
            if num not in existing:
                existing.add(num)
                account.account_number = num
                account.save(update_fields=["account_number"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_more_stocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.RunPython(update_accounts, reverse_code=migrations.RunPython.noop),
    ]
